### ISSUE TITLE
eos_eapi module does not correctly enable eAPI when using a vrf

### ISSUE THREAD

**Issue by sc68cal** [ansible-collections/arista.eos#57] opened 2020-06-12 20:24 UTC
##### SUMMARY

Using the defaults for `eos_api` does not render the proper configuration when using a VRF - it misses the `no shutdown` at the top of the configuration block that is required to start the eAPI server.

For example:

```yaml
    - name: Enable eAPI with no HTTP, HTTPS at port 443 in MGMT vrf
      eos_eapi:
        state: started
        http: false
        vrf: MGMT
```

Ends up rendering

```
management api http-commands
   vrf MGMT
      no shutdown
```

Which will not start the eAPI service.

```
config-mgmt-api-http-cmds)#show active
management api http-commands
   vrf MGMT
      no shutdown
(config-mgmt-api-http-cmds)#show management api http-commands
Enabled:            No
HTTPS server:       enabled, set to use port 443
HTTP server:        shutdown, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               None
Hits:               0
Last hit:           never
Bytes in:           0
Bytes out:          0
Requests:           0
Commands:           0
Duration:           0.000 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
```

Changing the configuration to be 

```
(config-mgmt-api-http-cmds)#show active
management api http-commands
   no shutdown
   !
   vrf MGMT
      no shutdown
```

Will successfully start the eAPI service

```
(config-mgmt-api-http-cmds)#show management api http-commands
Enabled:            Yes
HTTPS server:       running, set to use port 443
HTTP server:        shutdown, set to use port 80
Local HTTP server:  shutdown, no authentication, set to use port 8080
Unix Socket server: shutdown, no authentication
VRFs:               MGMT
Hits:               20
Last hit:           2 seconds ago
Bytes in:           3204
Bytes out:          219150
Requests:           20
Commands:           49
Duration:           15.111 seconds
SSL Profile:        none
FIPS Mode:          No
QoS DSCP:           0
Log Level:          none
CSP Frame Ancestor: None
TLS Protocols:      1.0 1.1 1.2
   User         Requests       Bytes in       Bytes out    Last hit
------------ -------------- -------------- --------------- -------------
   netbox       20             3204           219150       2 seconds ago

URLs
-------------------------------------
Management1 : https://<sanitized>:443
```

This has been tested on multiple versions of Arista EOS, with the same behavior on the tested versions

**Comment by GomathiselviS** [comment] 2020-06-17 16:41
Hi!

This is a duplicate of [issue](https://github.com/ansible/ansible/issues/51144
)
We believe recent commits  should resolve this question or problem for you.

This will also be included in the next major release.

A backport has been created in 2.9 as well , by this [PR](https://github.com/ansible/ansible/pull/70119)

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:

   * https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
   * https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Closed by GomathiselviS** 2020-06-17 16:41 UTC
