### ISSUE TITLE
Module defaults don't work

### ISSUE THREAD

**Issue by jhg03a** [ansible-collections/arista.eos#311] opened 2022-02-03 04:32 UTC
##### SUMMARY

When attempting to apply a module default for eos_facts, the defaults carried over into other modules as well leading them to break.

Based on the [documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html), I suspect that because the plugin routing for all action modules routes to `arista.eos.eos` the defaults for one module are being applied to all modules.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

arista.eos.eos

##### ANSIBLE VERSION

```paste below
bash-5.1# ansible --version
ansible [core 2.12.2]
  config file = /app/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /app/collections
  executable location = /usr/bin/ansible
  python version = 3.9.7 (default, Nov 24 2021, 21:15:59) [GCC 10.3.1 20211027]
  jinja version = 3.0.3
  libyaml = False
```

##### COLLECTION VERSION

```paste below
bash-5.1# ansible-galaxy collection list arista.eos

# /usr/lib/python3.9/site-packages/ansible_collections
Collection Version
---------- -------
arista.eos 3.1.0

# /app/collections/ansible_collections
Collection Version
---------- -------
arista.eos 4.0.0
```

##### CONFIGURATION

```paste below
bash-5.1# ansible-config dump --only-changed
COLLECTIONS_PATHS(env: ANSIBLE_COLLECTIONS_PATH) = ['/app/collections']
DEFAULT_REMOTE_USER(env: ANSIBLE_REMOTE_USER) = jhg03a
DEFAULT_ROLES_PATH(env: ANSIBLE_ROLES_PATH) = ['/app/roles']
DEFAULT_TIMEOUT(/app/ansible.cfg) = 30
HOST_KEY_CHECKING(/app/ansible.cfg) = False
PARAMIKO_HOST_KEY_AUTO_ADD(/app/ansible.cfg) = True
PARAMIKO_LOOK_FOR_KEYS(/app/ansible.cfg) = False
PERSISTENT_COMMAND_TIMEOUT(/app/ansible.cfg) = 90
PERSISTENT_CONNECT_TIMEOUT(/app/ansible.cfg) = 90
RETRY_FILES_ENABLED(/app/ansible.cfg) = False
USE_PERSISTENT_CONNECTIONS(/app/ansible.cfg) = True
```

##### OS / ENVIRONMENT

Control host is an alpine 3.15 container
"ansible_net_python_version": "3.9.7",
"ansible_net_system": "eos",
"ansible_net_version": "4.25.4M",
"ansible_net_model": "DCS-7280CR2A-60-F",
"ansible_net_api": "cliconf",

##### STEPS TO REPRODUCE

```yaml
- hosts: target_device
  connection: ansible.netcommon.network_cli
  gather_facts: false
  collections:
    - arista.eos

  module_defaults:
    arista.eos.eos_facts:
      gather_subset: all
      available_network_resources: true
      gather_network_resources:
        - all
        - '!bgp_address_family'
        - '!acls'

  tasks:
    - name: Get Facts
      eos_facts:

    - name: Get a copy of the startup config
      eos_command:
        commands: show startup-config
```

##### EXPECTED RESULTS

I expect module defaults to work

##### ACTUAL RESULTS

Using more than one EOS collection module with defaults set causes things to break.

```paste below
TASK [Get a copy of the startup config] **************************************************************************************************************************************************************************************************************************************
task path: /app/net.yml:52
redirecting (type: become) ansible.builtin.enable to ansible.netcommon.enable
<10.38.137.178> attempting to start connection
<10.38.137.178> using connection plugin ansible.netcommon.network_cli
Found ansible-connection at path /usr/bin/ansible-connection
<10.38.137.178> found existing local domain socket, using it!
<10.38.137.178> invoked shell using ssh_type: paramiko
<10.38.137.178> ssh connection done, setting terminal
<10.38.137.178> loaded terminal plugin for network_os arista.eos.eos
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> firing event: on_become
<10.38.137.178> firing event: on_open_shell()
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> ssh connection has completed successfully
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> Response received, triggered 'persistent_buffer_read_timeout' timer of 2.0 seconds
<10.38.137.178> updating play_context for connection
<10.38.137.178>
<10.38.137.178> local domain socket path is /root/.ansible/pc/2aa3d71d42
redirecting (type: action) arista.eos.eos_command to arista.eos.eos
redirecting (type: action) arista.eos.eos_command to arista.eos.eos
<10.38.137.178> ANSIBLE_NETWORK_IMPORT_MODULES: disabled
<10.38.137.178> ANSIBLE_NETWORK_IMPORT_MODULES: module execution time may be extended
<10.38.137.178> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.38.137.178> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-221vi2n24y `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984 `" && echo ansible-tmp-1643861835.8372083-146-76010885299984="` echo /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984 `" ) && sleep 0'
Using module file /app/collections/ansible_collections/arista/eos/plugins/modules/eos_command.py
<10.38.137.178> PUT /root/.ansible/tmp/ansible-local-221vi2n24y/tmp_uorgo37 TO /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984/AnsiballZ_eos_command.py
<10.38.137.178> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984/ /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984/AnsiballZ_eos_command.py && sleep 0'
<10.38.137.178> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984/AnsiballZ_eos_command.py && sleep 0'
<10.38.137.178> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-221vi2n24y/ansible-tmp-1643861835.8372083-146-76010885299984/ > /dev/null 2>&1 && sleep 0'
fatal: [rur01]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "available_network_resources": true,
            "commands": [
                "show startup-config"
            ],
            "gather_network_resources": [
                "all",
                "!bgp_address_family",
                "!acls"
            ],
            "gather_subset": "all",
            "interval": 1,
            "match": "all",
            "provider": null,
            "retries": 10,
            "wait_for": null
        }
    },
    "msg": "Unsupported parameters for (eos_command) module: available_network_resources, gather_network_resources, gather_subset. Supported parameters include: commands, interval, match, wait_for (waitfor), retries, provider."
}
```

**Comment by bcoca** [comment] 2022-02-17 15:50
dupe of https://github.com/ansible/ansible/issues/76687

Issue is due to using `redirect` (in runtime.yml), which creates an alias,  this is why the arguments are applied to all of them. 

It seems that what you really  want to do is use `use_redirected_action` to change the action plugin used, instead of forcing all plugins to appear as aliases of the same action plugin.

**Comment by nitzmahone** [comment] 2022-02-17 21:30
Definitely an unintended regression from the task action/module canonicalization stuff that happened with module_defaults in 2.12+; filed https://github.com/ansible/ansible/issues/77059 to look into ways to hopefully backwards-compatible ways to address it.

**Comment by bcoca** [comment] 2022-02-17 21:44
One workaround is removing the redirects from the runtime file and creating symlinks of the action plugin (target of redirect) to the module's name in `plugins/action`

remove
```
    eos_facts:
      redirect: arista.eos.eos
...
    eos_command:
      redirect: arista.eos.eos
```
and in the collection:

```
cd plugins/action
ln -s eos.py eos_command.py
ln -s eos.py eos_facts.py
```

**Comment by nitzmahone** [comment] 2022-02-17 21:47
That might make it work, but I wouldn't recommend that, as we've been trying to reduce use of symlinks throughout the Ansible codebase for a number of reasons. I'm hoping we can come up with a sane way to handle this in core...

**Comment by bcoca** [comment] 2022-02-17 21:48
'workaround' being key, you end up managing a LOT of symlinks

**Closed** 2022-03-17 13:42 UTC
