### ISSUE TITLE
ACL trouble with established tcp rule

### ISSUE THREAD

**Issue by michalkolar** [ansible-collections/arista.eos#139] opened 2021-01-07 08:13 UTC
Hi

I have a problem generating an ACL if the rules contain tcp flag established.

`  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py", line 932, in <module>
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py", line 927, in main
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py", line 89, in execute_module
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py", line 56, in get_acls_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py", line 110, in get_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py", line 78, in populate_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Fp0fOC/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py", line 310, in render_config
AttributeError: 'list' object has no attribute 'copy'
`

How to reproduce?

       - afi: ipv4
         acls:
         - name: test2
           aces:
           - sequence: 99
             grant: permit
             protocol: tcp
             source:
               any: yes
             destination:
               any: yes
             protocol_options:
               tcp:
                 flags:
                   established: yes
           - sequence: 200
             grant: permit
             protocol: tcp
             source:
               host: 1.2.3.4
             destination:
               host: 1.2.3.4
               port_protocol:
                 eq: "3389"
           - sequence: 300
             grant: permit
             protocol: udp
             source:
               any: yes
               port_protocol:
                 eq: "53"
             destination:
               any: yes
               port_protocol:
                 gt: "1023"
           - sequence: 400
             grant: deny
             protocol: ip
             source:
               any: yes
             destination:
               any: yes
       state: overridden

I edited ansible collections file ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py line 310 and replace copy() function with [:], works fine.

But I have another problem, when testing rule which I wrote at the beginning, parser not working ok.

If I run ansible multiple times ...

    "commands": [
        "ip access-list test2",
        "no 300",
        "99 permit tcp any any established",
        "200 permit tcp host 1.2.3.4 host 1.2.3.4 eq 3389",
        "400 deny ip any any",
        "300 permit udp any eq domain any gt 1023"
    ],

but when i delete ACL list from switch, first run is OK. This problem is in overridden and replaced writing mode.

**Comment by GomathiselviS** [comment] 2021-01-08 16:15
Hi @michalkolar , I used your playbook and verified using the state `merged, replaced and overridden`. I also gathered facts on a device, with acl rule `99 permit tcp any any established`. I did not encounter the error you have mentioned. I am not sure if I am missing anything from your config.

Can you please give more information on

-  playbooks you used
- after and before state of the device (execute the playbook with -vvvv option)
- which playbook resulted in the error you have mentioned
- ansible version

Once I have the information, I will be glad to work on the fix.

Thank you!

**Comment by michalkolar** [comment] 2021-01-08 18:08
- name: "Demonstrate connecting to switches"
  hosts: switches
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
   - name: override device configuration with  provided configuration
     arista.eos.eos_acls:
       config:
       - afi: ipv4
         acls:
         - name: test2
           aces:
           - sequence: 99
             grant: permit
             protocol: tcp
             source:
               any: yes
             destination:
               any: yes
             protocol_options:
               tcp:
                 flags:
                   established: yes
       state: replaced



ansible-playbook 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.16 (default, Oct 10 2019, 22:02:15) [GCC 8.3.0]
Using /etc/ansible/ansible.cfg as config file
setting up inventory plugins
host_list declined parsing /root/.ansible/inventory.yml as it did not pass its verify_file() method
script declined parsing /root/.ansible/inventory.yml as it did not pass its verify_file() method
Parsed /root/.ansible/inventory.yml inventory source with ini plugin
Loading callback plugin default of type stdout, v2.0 from /usr/lib/python2.7/dist-packages/ansible/plugins/callback/default.pyc
Skipping callback 'actionable', as we already have a stdout callback.
Skipping callback 'counter_enabled', as we already have a stdout callback.
Skipping callback 'debug', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'dense', as we already have a stdout callback.
Skipping callback 'full_skip', as we already have a stdout callback.
Skipping callback 'json', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'null', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.
Skipping callback 'selective', as we already have a stdout callback.
Skipping callback 'skippy', as we already have a stdout callback.
Skipping callback 'stderr', as we already have a stdout callback.
Skipping callback 'unixy', as we already have a stdout callback.
Skipping callback 'yaml', as we already have a stdout callback.

PLAYBOOK: test_pattern.yml ******************************************************************************************************************************************************************************************************************
Positional arguments: test_pattern.yml
become_method: sudo
inventory: (u'/root/.ansible/inventory.yml',)
forks: 5
tags: (u'all',)
verbosity: 4
connection: smart
timeout: 10
1 plays in test_pattern.yml

PLAY [Demonstrate connecting to switches] ***************************************************************************************************************************************************************************************************
META: ran handlers

TASK [override device configuration with  provided configuration] ***************************************************************************************************************************************************************************
task path: /root/.ansible/test_pattern.yml:9
<10.101.255.254> attempting to start connection
<10.101.255.254> using connection plugin ansible.netcommon.network_cli
<10.101.255.254> local domain socket does not exist, starting it
<10.101.255.254> control socket path is /root/.ansible/pc/cfb0b0a3ac
<10.101.255.254> local domain socket listeners started successfully
<10.101.255.254> loaded cliconf plugin ansible_collections.arista.eos.plugins.cliconf.eos from path /root/.ansible/collections/ansible_collections/arista/eos/plugins/cliconf/eos.py for network_os arista.eos.eos
<10.101.255.254>
<10.101.255.254> local domain socket path is /root/.ansible/pc/cfb0b0a3ac
<10.101.255.254> Using network group action arista.eos.eos for arista.eos.eos_acls
<10.101.255.254> ESTABLISH LOCAL CONNECTION FOR USER: root
<10.101.255.254> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-local-13273MTprro `"&& mkdir "` echo /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017 `" && echo ansible-tmp-1610129254.51-13280-231174987631017="` echo /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017 `" ) && sleep 0'
<fw> Attempting python interpreter discovery
<10.101.255.254> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'python3.5'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'python2.6'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<10.101.255.254> EXEC /bin/sh -c '/usr/bin/python && sleep 0'
<fw> Python interpreter discovery fallback (unsupported Linux distribution: debian)
Using module file /root/.ansible/collections/ansible_collections/arista/eos/plugins/modules/eos_acls.py
<10.101.255.254> PUT /root/.ansible/tmp/ansible-local-13273MTprro/tmpQR5ARQ TO /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py
<10.101.255.254> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/ /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py && sleep 0'
<10.101.255.254> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py && sleep 0'
<10.101.255.254> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py", line 102, in <module>
    _ansiballz_main()
  File "/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_acls', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python2.7/runpy.py", line 188, in run_module
    fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 82, in _run_module_code
    mod_name, mod_fname, mod_loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py", line 932, in <module>
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py", line 927, in main
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py", line 75, in execute_module
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py", line 56, in get_acls_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py", line 110, in get_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py", line 131, in get_network_resources_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py", line 78, in populate_facts
  File "/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py", line 310, in render_config
AttributeError: 'list' object has no attribute 'copy'
[WARNING]: Platform linux on host fw is using the discovered Python interpreter at /usr/bin/python, but future installation of another Python interpreter could change this. See
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information.
fatal: [fw]: FAILED! => {
    "ansible_facts": {
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-local-13273MTprro/ansible-tmp-1610129254.51-13280-231174987631017/AnsiballZ_eos_acls.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.arista.eos.plugins.modules.eos_acls', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py\", line 932, in <module>\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/modules/eos_acls.py\", line 927, in main\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py\", line 75, in execute_module\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/config/acls/acls.py\", line 56, in get_acls_facts\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/facts.py\", line 110, in get_facts\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/ansible/netcommon/plugins/module_utils/network/common/facts/facts.py\", line 131, in get_network_resources_facts\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py\", line 78, in populate_facts\n  File \"/tmp/ansible_arista.eos.eos_acls_payload_Bhul7E/ansible_arista.eos.eos_acls_payload.zip/ansible_collections/arista/eos/plugins/module_utils/network/eos/facts/acls/acls.py\", line 310, in render_config\nAttributeError: 'list' object has no attribute 'copy'\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}

PLAY RECAP **********************************************************************************************************************************************************************************************************************************
fw                         : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by GomathiselviS** [comment] 2021-01-08 19:27
Hi @michalkolar  Thanks for providing the information.  The issue is seen when the play is executed in python 2.7 env . A PR is up with the fix.

**Comment by michalkolar** [comment] 2021-01-09 09:08
Hi @GomathiselviS thanks you.


Now i have problem with sorting command to rewrite switch ACL.


for example in overridden:

`- name: "Demonstrate connecting to switches"
  hosts: switches
  gather_facts: no

  tasks:
    ###
    # Collect data
    #
   - name: override device configuration with  provided configuration
     arista.eos.eos_acls:
       config:
       - afi: ipv4
         acls:
         - name: test2
           aces:
           - sequence: 99
             grant: permit
             protocol: tcp
             source:
               any: yes
             destination:
               any: yes
             protocol_options:
               tcp:
                 flags:
                   established: yes
           - sequence: 200
             grant: permit
             protocol: tcp
             source:
               host: 185.174.171.144
             destination:
               host: 185.174.171.133
               port_protocol:
                 eq: "3389"
       state: overridden
`

when in switch exist this rules make command with non-logic...

https://pastebin.com/6AXz9rmM

when change state to "replaced"

https://pastebin.com/z80AvCFJ

**Closed** 2021-01-21 15:47 UTC

**Comment by michalkolar** [comment] 2021-01-22 22:06
Hi @GomathiselviS ,

any news?
